services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    user: "1000:1000"
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https 
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - XDG_CACHE_HOME=/home/node/.cache
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_SQLITE_POOL_SIZE=2
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_API_KEY_AUTH_ENABLED=true
      - N8N_PUBLIC_API_DISABLED=false
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./local-files:/files
      - ./n8n_cache:/home/node/.cache

  filebrowser:
    image: filebrowser/filebrowser
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /mnt/storage/nas/shared:/srv
      - /home/admin/filebrowser/database.db:/database.db
    environment:
      - FB_DATABASE=/database.db
      - FB_ROOT=/srv

